### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Sethyboi1** [Universal-Team/LeafEdit#38] opened 2020-12-12 15:53 UTC
**Describe the bug**
Trying to edit villagers crashes my 3DS.
**To Reproduce**
1. Go to Editor.
2. Click on Villagers.
3. Select a Villager.
4. Crash Dump.

It just shows a crash dump. "Press A to save the crash dump. Press any other button to shutdown."

**Console (please complete the following information):**
  - [ ] 3DS
  - [x] New 3DS

  - Luma 3DS Version [e.g. v9.1]

  - [x] CIA
  - [ ] 3DSX

**LeafEdit (please complete the following information):**
  - [ ] Release

If Release -> Version [e.g. v0.1.0]

  - [x] Nightly

If Nightly -> Commit Hash [e.g. f52c458]

**Additional context**

**Comment by SuperSaiyajinStackZ** [comment] 2020-12-12 16:13
Try the latest Nightly or Release. I cannot reproduce it on the latest Release or Nightly.

**Comment by SuperSaiyajinStackZ** [comment] 2020-12-12 16:24
Ah nevermind. I was able to reproduce it now. I might fix it in the next days or so when i get to it, since my focus is on the ACWW-Web-SaveEditor right now.

**Comment by SuperSaiyajinStackZ** [comment] 2020-12-12 16:50
Seems like for the latest Nightly, it was just a string path derp and accessed out of bounds. Should be fixed with [31d93ff](https://github.com/Universal-Team/LeafEdit/commit/31d93ff44583dbeac745a791e6baa2acb83be9a1). Check the latest Nightly now, i cannot reproduce the issue on my end anymore. Also to make sure, which game? New Leaf? Wild World?

**Comment by Sethyboi1** [comment] 2020-12-12 17:49
oh yeah sorry it was new leaf. forgot to mention that. thx for fixing it ill go install it rn! (:

**Closed** 2020-12-13 00:13 UTC
Labels: bug
